# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: GDG Baroda 
email: manan@gdgbaroda.com
description: An open-for-all and diverse developer community
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://gdgbaroda.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: "@gdgbaroda"
github_username:  gdgbaroda
facebook_url:  "https://facebook.com/GDGBaroda"
youtube_url: "https://www.youtube.com/channel/UCdAjNjPWNIXNaxu4mGJc3uw"
meetup_url: "https://www.meetup.com/gdgbaroda/"
join_url: "http://bit.ly/gdgbaroda_slack"

defaults:
  - 
    scope:
      path: ""
    values:
      image: cover-image-team.jpg

# Build settings
markdown: kramdown
future: true
permalink: /:categories/:title/
sass:
  sass_dir: _scss
gems:
  - jekyll-feed
  - jekyll-seo-tag
timezone: 'Asia/Kolkata'
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
